name: steam-api
region: ams
services:
- dockerfile_path: Steam.Api/Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: Phoenix-Network-Ltd/Steam.Api
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: steam-api
  routes:
  - path: /